#ifndef RENDERINGMANAGER_HPP
#define RENDERINGMANAGER_HPP

	#include "RenderTriangle.hpp"
	#include "RenderRectangle.hpp"

	///
	/// Define all rendering element type
	/// that can be generated by the Manager.
	///
	enum ShapeType
	{
		RM_SHAPE_TRIANGLE = 0,
		RM_SHAPE_RECTANGLE,
		RM_SHAPE_NUMBER
	};

	class RenderingManager
	{
		public:
			///
			/// Constructor.
			///
			RenderingManager();

			///
			/// Destructor.
			///
			~RenderingManager();

			///
			/// Create a new and return a new buffered Shape. 
			///
			RenderShape* getNewBufferedShape(ShapeType const);

		private:
			///
			///
			///
			static GLuint buffers[];

			///
			///
			///
			RenderShape* getNewShape(ShapeType const);

	};

#endif
